M48
; DRILL file KiCad 10.0.4-10.0.4~ubuntu25.10.1 date 2026-07-20T14:28:49
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-07-20T14:28:49+00:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.4-10.0.4~ubuntu25.10.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
%
G90
G05
T1
X157.523Y-87.21
X163.303Y-87.21
M30
