M48
; DRILL file KiCad 10.0.4-10.0.4~ubuntu25.10.1 date 2026-07-13T09:37:08
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-07-13T09:37:08+00:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.4-10.0.4~ubuntu25.10.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
%
G90
G05
T1
X159.835Y-84.136
X165.615Y-84.136
M30
